language: php

matrix:
  include:
    - php: 7.4
      env: INLCUDE_COVERAGE='true'
    - php: nightly

  allow_failures:
    - php: nightly

  fast_finish: true

# Shallow clones can cause issues with subtree splits
git:
  depth: false

before_script:
  - if [ "$INLCUDE_COVERAGE" == 'true' ] && [ php -v | grep -q 'Xdebug' ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$INLCUDE_COVERAGE" == 'true' ]; then pecl install pcov; fi
  - composer self-update
  - composer install
  - composer dump-autoload -o

script:
  - if [ "$INLCUDE_COVERAGE" != 'true' ]; then vendor/bin/phpunit; fi
  - if [ "$INLCUDE_COVERAGE" == 'true' ]; then vendor/bin/phpunit --coverage-clover ./.coverage/clover.xml --verbose; fi
  - if [ "$INLCUDE_COVERAGE" == 'true' ]; then composer run-script lint-check; fi

after_success:
  - if [ "$INLCUDE_COVERAGE" == 'true' ]; then vendor/bin/php-coveralls --coverage_clover=./.coverage/clover.xml --json_path=./coveralls-upload.json -v; fi

deploy:
  - provider: script
    script: bash bin/split.sh $TRAVIS_BRANCH $GIT_USER $GIT_ACCESS_TOKEN $TRAVIS_TAG
    on:
      branch: master
    skip_cleanup: true

notifications:
  email:
    - dave@aphiria.com

sudo: false
